### ISSUE TITLE
Needs tests

### ISSUE THREAD

**Issue by DanielStevenLewis** [yusinto/ld-react#1]
Love this library. Great design. I hope LaunchDarkly ends up officially supporting it because it's way better than the alternatives (e.g., https://launchdarkly.com/blog/implementing-feature-flags-in-single-page-apps-using-react-and-redux-saga/ , https://github.com/TrueCar/react-launch-darkly ).

That being said, it needs tests.

**Comment by yusinto** [comment]
Good point. I will add tests. Thanks for the feedback.

**Comment by yusinto** [comment]
I've added tests to [v2.0.0-alpha.2](https://github.com/yusinto/ld-react/releases/tag/v2.0.0-alpha.2) along with hooks support.
